const hints = [
    'Do you like rain?',
    'How do you feel when it rains?',
    'What kind of rain do you like?',
    'Do you like rainy season?',
    'What do you do to enjoy rain or rainy season?',
    'Do you have any story to tell related to rain?',
    'What kind of umbrella do you like to use?',
    'Do you like to use a folding umbrella?',
    'What color of umbrella do you most like to use? And why?',
    'How do you like to dress when it rains?',
    'Can you explain where rain comes from and how it is formed?',
    'Can you explain how rainbow is formed?',
    'What is your favorite song or lyrics about rain?',
    'Can you explain the meaning of the phrase "When it rains, it pours."',
    'What is the origin of the phrase "it\'s raining cats and dogs?"',
    'What is the origin of the phrase "I\'ll take a rain check"?',
    'Can you explain what the idiom "rain or shine" means?',
    'Try to make a sentence using the idiom "rain or shine".',
    'Have you ever thought about becoming a teacher? Why? Why not?',
    'Do you like to teach? Why? Why not?',
    'Do you like to be taught by someone or learn by yourself?',
    'Please talk about a good teacher you had before.',
    'Why do you think he or she was a good teacher?',
    'Please talk about a bad teacher you had before.',
    'Why do you think he or she was a bad teacher?',
    'If you were going to to be a teacher,where and what would you want to teach?',
    'If you were going to be a student again, where and what would you want to learn?',
    'Do you think you need a teacher to learn a foreign language? Why? Why not?',
    'What do you expect from your language teacher to learn a language?',
    'What else is important to learn a foreign language in addition to a good teacher?',
    'What are the differences among teaching, training, and educating?',
    'Would you rather be a teacher, trainer or educator?',
    'Which do you like better? Instrumental music or songs? Why? What is the first CD you bought?',
    'What is the last CD you bought?',
    'What song did you like when you were a child?',
    'Tell me about your favorite song. Why do you like this song? What does the song remind you?',
    'When do you feel like listening to the song?',
    'What songs do you often listen to?',
    'What song do you want to listen to you feel down?',
    'What song do you listen to when you feel happy?',
    'What song do you listen to when you commute?',
    'What song do you like to listen to when you are exercising? Do you like karaoke? Why? Why not?',
    'Where or when do you feel like singing?',
    'Have you thought about making your own song? Why? Why not?',
    'What song do you feel like listening to or singing today?',
    'What song from your country or in your own language do you like?',
    'Tell me about your favorite piece of lyrics. Why do you like it?',
    'Do you like English songs? What English song do you like?',
    'Have you ever used English songs for studying English? Did it help? What song did you use to study English?',
    'Do you like spring?',
    'Why or why not?',
    'How do you like do dress in spring?',
    'Do you have hay fever? What do you do to deal with hay fever?',
    'What do people do in spring in your country?',
    'What do you like about spring most and least?',
    'Do you feel physically sick when spring comes?',
    'Do you feel positive or optimistic in spring? How?',
    'What is your most favorite season of the year? Why? (According to a survey, about 30% of Americans like fall)',
    'What is your favorite food, and what is your favorite drink to go with that food? ',
    'Do you cook? If so, how often?',
    'Have you ever joined a cooking school or circle? how was it?',
    'Please describe your favorite recipe.',
    'Do you have any unique eating habits?',
    'Is it important for you to eat healthy?',
    'Can you explain what healthy eating is?',
    'Do you think skipping breakfast is bad for health? ',
    'Do you eat or drink a lot when you are stressed? ',
    'Do you watch your daily calorie intake when you choose what to eat? How do you check it? ',
    'Do you like to have ramen after drinking at night? ',
    'What is the cheapest place to eat you know? How often do you eat there?',
];

export default hints;
